title: Ehsaan Ali
logo: assets/img/EhsaanAli22I-0004 MSAI.jpeg
#description: text below image
linkedin: "https://www.linkedin.com/in/ehsaan-ali-nagyal/"
show_downloads: true
theme: jekyll-theme-leap-day
