title: Ehsaan Ali
logo: assets/img/ehsaan.jpg
#description: text below image
author:
  linkedin         : " https://www.linkedin.com/in/ehsaan-ali-nagyal/ "
show_downloads: true
theme: jekyll-theme-minimal
